// Equivalent to "index.html", but written in React instead
import React, { Fragment } from 'react';
import { useState, useEffect } from 'react';
import { config, useSpring, animated } from 'react-spring'
import ReactDOM from 'react-dom';
import Head from 'next/head'
import Menu from '../components/menu'
import Blob from '../components/blob'
import Nav from '../components/nav'
import Wave from 'react-wavify'
import styles from '../styles/Home.module.css'
import { Container } from '@chakra-ui/react'
import { Flex, Spacer } from '@chakra-ui/react'
import { Stack, Button, Icon, HStack, Box, Avatar, Image, Text, ButtonGroup } from '@chakra-ui/react'
import { Heading } from '@chakra-ui/react'
import { Grid, GridItem } from '@chakra-ui/react'
import { EmailIcon, ArrowForwardIcon } from '@chakra-ui/icons'

// Function is identical to the one found in components/blob.js, except color differs slightly
function Morph({x}){
  return (
      <svg
        viewBox="0 0 100 100"
        height="auto"
        width="100%"
        id="sw-js-blob-svg"
        className={styles.organicimage}
      >
        <defs> 
            <linearGradient id="sw-gradient-sun" x1="0" x2="1" y1="1" y2="0">
                <stop id="stop1" stopColor="rgba(251, 168, 31, 1)" offset="0%"></stop>
                <stop id="stop2" stopColor="rgba(248, 117, 55, 1)" offset="100%"></stop>
            </linearGradient>
        </defs>
        <animated.path
          fill="url(#sw-gradient-sun)"
          d={x.to({
            range: [0, 1],
            output: [
              "M22.4,-25.6C28.8,-21.3,33.6,-14.1,31.9,-8C30.2,-1.9,21.9,3,16.5,6.9C11.1,10.8,8.6,13.8,5.3,15.2C2,16.6,-2,16.6,-4.2,14.5C-6.5,12.4,-6.9,8.3,-9.3,5C-11.8,1.6,-16.2,-1,-18.7,-6.1C-21.2,-11.2,-21.7,-18.8,-18.2,-23.6C-14.8,-28.5,-7.4,-30.5,0.3,-30.9C8,-31.3,16,-29.9,22.4,-25.6Z",
              "M23.5,-28.7C29.6,-22.8,33.3,-14.7,35.5,-5.7C37.8,3.3,38.7,13,35.3,21.7C31.9,30.3,24.2,37.8,15.7,39.2C7.2,40.7,-2.1,36,-10.8,31.9C-19.5,27.7,-27.6,24.2,-32.2,17.8C-36.8,11.4,-37.9,2.3,-35.4,-5.3C-33,-12.9,-27,-19,-20.5,-24.8C-14,-30.6,-7,-36.3,0.8,-37.3C8.7,-38.3,17.3,-34.6,23.5,-28.7Z",
            ],
          })}
          width="100%" height="100%" transform="translate(50 50)" stroke-width="0"
        />
      </svg>
  );
}

function Home() {
  const [active, setActive] = useState(false);
  const { x } = useSpring({ config: { duration: 800 }, x: active ? 1 : 0 });
  return (
    <div className={styles.container} height="100vh">
      <Head>
        <title>Home | Harvey Zheng</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid templateColumns='repeat(5, 1fr)' gap={4}>
        <GridItem 
          colStart={1} 
          className={styles.heroContainer}
          colEnd={6} 
          >
          <Nav/>
          <Flex justify="space-around" direction="column" align="center">
            <Flex className="flex-col lg:flex-row">
              <Flex direction="column" justify="center">
                <Heading color="#13293D">
                  Hi, I'm Harvey!
                </Heading>
                <Text as='i' fontSize='2xl' color="#13293D">
                    CMU Stat ML + HCI &apos;23
                </Text>
              </Flex>
                
              <Box className={styles.organiccontainer}>
                <Image src="../images/portrait.jpeg"
                  borderRadius="full"
                  className={`md:w-1/2 ${styles.organicOverlayPortrait}`}
                  onMouseEnter={() => setActive(true)}
                  onMouseLeave={() => setActive(false)}
                  />
                <Morph x={x}/>
              </Box>
            </Flex>
          </Flex>
          <Wave fill='#2A4365'
            style={{display: "block", height: "100%"}}
            paused={false}
            options={{
              height: 40,
              amplitude: 40,
              speed: 0.2,
              points: 3
            }}
            />
          </GridItem>
      </Grid>
      <Container maxW='container.xl'>
        <Flex className="flex-col md:flex-row items-center md:items-start">
          <Flex direction="column">
            <Menu index={0}/>
          </Flex>
          <Flex grow={1} direction="column" justify="center" className={styles.mainContent}>
            <Box marginBottom="60px">
              <Heading className="text-center md:text-left md:ml-4">Featured Projects</Heading>
            </Box>
            <Blob
              blobPath1={1}
              blobPath2={2}
              link="/ux/happy-pawz"
              projectName='Test Project'
              projectDesc='This is a brief description of the project. 
              In this section, we want to describe the benefits of the project, 
              how we did the project, and design decisions made throughout the project'
              reverse="row"
              />
            <Blob
              blobPath1={2}
              blobPath2={3}
              projectImage="test.png"
              link="/ux"
              projectName='Test Project'
              projectDesc='This is a brief description of the project. 
              In this section, we want to describe the benefits of the project, 
              how we did the project, and design decisions made throughout the project'
              reverse="row-reverse"
              />
            <Blob
              blobPath1={1}
              blobPath2={0}
              projectImage="test.png"
              link="/ux"
              projectName='Test Project'
              projectDesc='This is a brief description of the project. 
              In this section, we want to describe the benefits of the project, 
              how we did the project, and design decisions made throughout the project'
              reverse="row"
              />
          </Flex>
        </Flex>
      </Container>
      
    </div>
  )
}

export default Home;